export const API_ERRORS = {
  UNAUTHORIZED: 'Unauthorized',
  FORBIDDEN: 'Forbidden',
  NOT_FOUND: 'Not found',
  VALIDATION_FAILED: 'Validation failed',
  TOO_MANY_REQUESTS: 'Too many requests',
  RESTAURANT_NOT_FOUND: 'Restaurant not found',
  REVIEW_NOT_FOUND: 'Review not found',
  DISH_NOT_FOUND: 'Dish not found',
  USER_NOT_FOUND: 'User not found',
  ALREADY_REVIEWED: 'You have already reviewed this dish',
  ALREADY_FLAGGED: 'You have already flagged this review',
  FAILED_TO_CREATE_REVIEW: 'Failed to create review',
  FAILED_TO_UPDATE_REVIEW: 'Failed to update review or unauthorized',
  FAILED_TO_DELETE_REVIEW: 'Failed to delete review or unauthorized',
  INSUFFICIENT_POINTS: 'Insufficient DishPoints',
  COUPON_UNAVAILABLE: 'Coupon no longer available',
  PAYMENT_FAILED: 'Payment verification failed',
  RESTAURANT_ALREADY_OWNED: 'Restaurant already has an owner',
  PENDING_CLAIM_EXISTS: 'A pending claim already exists for this restaurant',
  DISH_ID_REQUIRED: 'dishId is required',
  FAILED_TO_FLAG_REVIEW: 'Failed to flag review',
  FAILED_TO_VOTE_HELPFUL: 'Failed to vote helpful',
  FAILED_TO_ACTIVATE_PREMIUM: 'Failed to activate premium',
  FAILED_TO_FETCH_DATA: 'Failed to fetch data',
  CLAIM_NOT_FOUND: 'Claim not found',
  CLAIM_ALREADY_REVIEWED: 'Claim has already been reviewed',
  CLAIM_ID_REQUIRED: 'claimId is required',
  NOTIFICATION_NOT_FOUND: 'Notification not found',
  FAILED_TO_MARK_READ: 'Failed to mark notification as read',
  FAILED_TO_MARK_ALL_READ: 'Failed to mark notifications as read',
  FAILED_TO_APPROVE_REVIEW: 'Failed to approve review',
  FAILED_TO_DELETE_REVIEW_ADMIN: 'Failed to delete review',
  FAILED_TO_FETCH_CLAIMS: 'Failed to fetch claims',
  FAILED_TO_REVIEW_CLAIM: 'Failed to review claim',
  FAILED_TO_FETCH_COUPONS: 'Failed to fetch coupons',
  FAILED_TO_CREATE_COUPON: 'Failed to create coupon',
  FAILED_TO_DEACTIVATE_COUPON: 'Failed to deactivate coupon',
  FAILED_TO_FETCH_BALANCE: 'Failed to fetch balance',
  FAILED_TO_REDEEM_COUPON: 'Failed to redeem coupon',
  FAILED_TO_CREATE_ORDER: 'Failed to create order',
  FAILED_TO_UPDATE_PREMIUM: 'Failed to update premium role',
  FAILED_TO_UPDATE_ADMIN: 'Failed to update admin role',
  FAILED_TO_FETCH_TRANSACTIONS: 'Failed to fetch transactions',
  FAILED_TO_UPDATE_REQUEST: 'Failed to update dish request',
  MISSING_SIGNATURE: 'Missing signature',
  INVALID_SIGNATURE: 'Invalid signature',
  INVALID_JSON: 'Invalid JSON',
  WEBHOOK_FAILED: 'Webhook processing failed',
  RESTAURANT_OWNER_EXISTS: 'This restaurant already has a verified owner',
  FAILED_TO_SAVE_DISH: 'Failed to save dish',
  FAILED_TO_REMOVE_DISH: 'Failed to remove dish',
  INVALID_QUERY_PARAMS: 'Invalid query parameters',
} as const

export const CLIENT_ERRORS = {
  SOMETHING_WENT_WRONG: 'Something went wrong',
  SOMETHING_WENT_WRONG_RETRY: 'Something went wrong. Please try again.',
  COULD_NOT_UPDATE_WISHLIST: 'Could not update wishlist',
  COULD_NOT_MARK_HELPFUL: 'Could not mark as helpful',
  COULD_NOT_REPORT_REVIEW: 'Could not report review',
  FAILED_TO_LOAD_ANALYTICS: 'Failed to load analytics',
  DELETE_FAILED: 'Delete failed',
} as const
