export const ROUTES = {
  HOME: '/',
  EXPLORE: '/explore',
  LOGIN: '/login',
  SIGNUP: '/signup',
  MY_PROFILE: '/my-profile',
  SETTINGS: '/settings',
  WISHLIST: '/wishlist',
  NOTIFICATIONS: '/notifications',
  REWARDS: '/rewards',
  WRITE_REVIEW: '/write-review',
  ONBOARDING: '/onboarding',
  UPGRADE: '/upgrade',
  COMPARE: '/compare',
  REVIEW_SUCCESS: '/review-success',
  FORGOT_PASSWORD: '/forgot-password',
  ADMIN: '/admin',
  ADMIN_USERS: '/admin/users',
  ADMIN_REVIEWS: '/admin/reviews',
  ADMIN_REQUESTS: '/admin/requests',
  ADMIN_COUPONS: '/admin/coupons',
  ADMIN_CLAIMS: '/admin/restaurant-claims',
  dish: (id: string) => `/dish/${id}`,
  restaurant: (id: string) => `/restaurant/${id}`,
  cuisine: (slug: string) => `/cuisine/${slug}`,
  review: (id: string) => `/review/${id}`,
  writeReviewForDish: (params: string) => `/write-review?${params}`,
  restaurantDashboard: (id: string) => `/restaurant-dashboard/${id}`,
  restaurantDashboardDishes: (id: string) => `/restaurant-dashboard/${id}/dishes`,
  claimRestaurant: (id: string) => `/claim-restaurant/${id}`,
  loginWithRedirect: (redirect: string) => `/login?redirect=${redirect}`,
  profile: (userId: string) => `/profile/${userId}`,
  exploreWithQuery: (q: string) => `/explore?q=${q}`,
} as const
